export * from './getPurchases.interface'
export * from './getPurchaseById.interface'
export * from './getPurchasesByCustomer.interface'
export * from './getPurchasesByDate.interface'
export * from './getPurchasesByStatus.interface'
export * from './getPurchasesByProductName.interface'
export * from './addPurchase.interface'
export * from './deletePurchase.interface'